# Generated by Django 2.1.5 on 2025-01-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250129_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
    ]
